spring:
  config:
    import: "optional:configserver:http://localhost:9200/"
  kafka:
    bootstrap-servers: localhost:9092

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9201/eureka/