apiVersion: v1
kind: Namespace
metadata:
  name: group1-team3
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper
  namespace: group1-team3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
        - name: zookeeper
          image: bitnami/zookeeper:latest
          ports:
            - containerPort: 2181
            - containerPort: 2888
            - containerPort: 3888
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  namespace: group1-team3
spec:
  ports:
    - port: 2181
      targetPort: 2181
    - port: 2888
      targetPort: 2888
    - port: 3888
      targetPort: 3888
  selector:
    app: zookeeper
