spring:
  config:
    import: "optional:configserver:http://team3-lsc-configserver-service:80/"
  kafka:
    bootstrap-servers: kafka.group1-team3:9092

eureka:
  client:
    serviceUrl:
      defaultZone: http://team3-lsc-eurekaserver-service:80/eureka/